### ISSUE TITLE
(High) Github OAuth를 통한 Login 기능 구현

### ISSUE THREAD

**Issue by Alencion** [teamTenta/Tenta#2]
Github OAuth Login 구현

- [x] dependency 추가
- [x] User Entity 생성
- [x] login API

**Comment by DoDaek** [comment]
OAuth관련해서 [Spring Boot Tutorial](https://spring.io/guides/tutorials/spring-boot-oauth2/)이 있길래 남겨봅니다.
관련 Tutorial도 Github Social Login 기능구현이라 참고가 될 듯 합니다.

**Comment by DoDaek** [comment]
미안합니다. 실수로 Issue를 Close했습니다.
